<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRE9dHa9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRE9dHa9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRE9dHa9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRE9dHa9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRE9dHa9\App_KernelDevDebugContainer([
    'container.build_hash' => 'RE9dHa9',
    'container.build_id' => '71152edb',
    'container.build_time' => 1605626634,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRE9dHa9');
