<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container98rxQfZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container98rxQfZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container98rxQfZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container98rxQfZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container98rxQfZ\App_KernelDevDebugContainer([
    'container.build_hash' => '98rxQfZ',
    'container.build_id' => '58cddd7e',
    'container.build_time' => 1605562684,
], __DIR__.\DIRECTORY_SEPARATOR.'Container98rxQfZ');
