<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFowldr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFowldr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIFowldr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIFowldr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIFowldr\App_KernelDevDebugContainer([
    'container.build_hash' => 'IFowldr',
    'container.build_id' => '1bedbcec',
    'container.build_time' => 1605627681,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFowldr');
